import type { Metadata } from 'next';
import Link from 'next/link';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Image from 'next/image';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="px-4 py-2 bg-transparent absolute flex flex-row justify-between w-full items-center z-5">
          <Image
            src={'/logo.svg'}
            width={100}
            height={0}
            alt={'hero'}
            className={'size-fit max-w-1/5'}
          />
          <nav className="flex text-lg text-zinc-100">
            <Link href={'/'}>
              <button className="px-3 py-1 hover:bg-zinc-50 hover:text-zinc-600 hover:cursor-pointer">
                Home
              </button>
            </Link>

            <button className="px-3 py-1 hover:bg-zinc-50 hover:text-zinc-600 hover:cursor-pointer">
              Explore
            </button>
            <button className="px-3 py-1 hover:bg-zinc-50 hover:text-zinc-600 hover:cursor-pointer">
              Trips
            </button>
            <button className="px-3 py-1 hover:bg-zinc-50 hover:text-zinc-600 hover:cursor-pointer">
              Settings
            </button>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
